### ISSUE TITLE
Mises à jour des personnalisations faites pour 15.04.3 et discoeasy200

### ISSUE THREAD

**Issue by arthurlutz** [dagoma3d/CuraByDagoma#1]
https://dagoma.fr/logiciels.html affiche des logiciels pour mis à jour pour la discoeasy200 et des nouvelles versions de cura. Pourtant ce dépôt n'a pas bougé depuis 2 ans. 

Je pense que ça pourrait être profitable à vos utilisateurs et à votre image de publier ces personnalisations ici (au delà du fait que la https://github.com/Ultimaker/Cura/blob/master/LICENSE vous y oblige probablement), à moins que ce ne soit publié ailleurs ?

**Comment by dagomafr** [comment]
Bonjour Arthur,

Tu as tout à fait raison, cela va être fait bientôt.

Cordialement,
Orel

**Comment by arthurlutz** [comment]
Très bonne nouvelle. Merci d'avance.

**Comment by arthurlutz** [comment]
pouvez vous m'indiquer pourquoi ce ticket a été fermé ? est-il en "wontfix" ou résolu ?

**Comment by 0r31** [comment]
Bonjour Arthur,

Il est résolu. Toutes les sources sont à jour que ce soit pour CuraByDagoma ou CuraEngine.
Cela fait longtemps que c'est le cas.

**Comment by dagoma3d** [comment]
Ce ticket est clos car les sources publiées ici sont maintenant à jour.
