### ISSUE TITLE
mauvais chemin raccourcis CBD

### ISSUE THREAD

**Issue by denisdago** [dagoma3d/CuraByDagoma#126]
après l'installation de cbd 2.2.0, l'icone sur le bureau ne lance pas le logiciel quand on double clique dessus
quand on clique droit sur l'icone, le paramètre "Démarrer dans ..." contenait "drivers"  , pourtant lors de l'install seul le dossier destination a été créé et choisi

**Comment by 0r31** [comment]
Fixed by https://github.com/dagoma3d/CuraByDagoma/commit/946f3ac8c827c5f2ef24c4956e3d8b172a93d156
