### ISSUE TITLE
Add the ability to custom the first layer temperature

### ISSUE THREAD

**Issue by 0r31** [dagoma3d/CuraByDagoma#13]
As a user, i want to have the ability to choose the temperature of the first layer.
It should be useful when using geckotek adhesion stuff as the current temperature is a bit hot.

**Comment by 0r31** [comment]
A way to do that is to use the gcode post-processing stuff in curabydago.

**Comment by Alutulu** [comment]
TODO : when PR #71 merged, add the factorize function in ```OnFirstTempCheckBoxChanged```
