### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by 0r31** [dagoma3d/CuraByDagoma#20]
We have to update all tools and processes to build a valid installer from python3 sources.

**Comment by 0r31** [comment]
First step : Update NSIS from 2.x to 3.x.

**Comment by 0r31** [comment]
Steps to initialize a ready to use virtual env : 
- Install python 3.9
- Create a virtual env : `python -m venv myvenv` and activate it.
- Install common dependencies : `pip install numpy pyserial`
- Get / install specific wheel for PyOpenGL (PyOpenGL‑3.1.6‑cp39‑cp39‑win_amd64.whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl)
- Get  / install specific wheel for wxPython (https://files.pythonhosted.org/packages/6f/d3/155ce684967bba904a9d29c346430a491643d60a23f713fcf2fa981b7855/wxPython-4.1.1-cp39-cp39-win_amd64.whl)

**Comment by 0r31** [comment]
Next step will be to modify the **windows** section in [package.sh](https://github.com/dagoma3d/CuraByDagoma/blob/migration_python3/package.sh) in order to leverage the virtual environment we previously created.

**Comment by BlessingCR** [comment]
The website down.  https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl

**Comment by 0r31** [comment]
![image](https://github.com/dagoma3d/CuraByDagoma/assets/37673727/70e90250-a481-4f8f-99bf-125833704c26)
