### ISSUE TITLE
Socket closed too soon

### ISSUE THREAD

**Issue by 0r31** [dagoma3d/CuraByDagoma#22]
In some circumstances, we have to deal with the current exception raising :

`OSError: [WinError 10038] an operation was attempted on something that is not a socket`

It is raised in [sliceEngine.py, line 205](https://github.com/dagoma3d/CuraByDagoma/blob/5e34f5567c2555e97af5e6db3b82b9306bde443d/Cura/util/sliceEngine.py#L205).

It seems the socket is closed too soon.

Similar issue : https://stackoverflow.com/questions/15210178/python-socket-programming-oserror-winerror-10038-an-operation-was-attempted-o

**Comment by Alutulu** [comment]
This bug haven't happened anymore. More tests are needed.
