### ISSUE TITLE
Update NSIS tool

### ISSUE THREAD

**Issue by 0r31** [dagoma3d/CuraByDagoma#29]
We currently using an old NSIS 2.x version to build the Windows installer.
Will try to migrate to NSIS 3.x.

**Comment by Alutulu** [comment]
https://stackoverflow.com/questions/39600044/nsis-2-51-to-3-0-upgrade

**Comment by Alutulu** [comment]
Docs about NSIS syntax : https://nsis.sourceforge.io/Docs/

**Comment by Alutulu** [comment]
Wiki : https://nsis.sourceforge.io/Main_Page
