### ISSUE TITLE
Windows + Python3 : Gestion de la carte sd

### ISSUE THREAD

**Issue by 0r31** [dagoma3d/CuraByDagoma#49]
Sous windows, depuis la branche **migration_python3**, une carte sd insérée n'est pas reconnue par CuraByDagoma.

**Comment by Alutulu** [comment]
![image](https://user-images.githubusercontent.com/102467914/173087470-89a24c14-b09d-4d22-b667-92a209c9911d.png)
```windll.kernel32.GetDriveTypeA('D:/')``` should return 2, but returns 1 here.
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdrivetypea

**Comment by Alutulu** [comment]
In branch "detect_SD-card", problem is nearly solved. It works well, but from the second time we save the g-code file. At the first time, it doesn't detect the SD card.
